# Note: You need to create the database before setting this up.

mysql:
  ip: 34.87.27.102
  port: 3306
  database: "minecraftbe"
  username: "root"
  password: "matkhau8kytu"
#tinh theo %
discount: 150
fix: false
joinscreen:
  title: "RootSkyBlock"
  des: "sdfsdfsdfsdfsdf"

eventscreen:
  title: "RootSkyBlock"
  des: "sdfsdfsdfsdfsdf"