name: "RootCore"
version: 1.0.0
api: ["1.0.8"]
author: "TanToan99"
description: "RootCore for RootNetWorld - Minecraft BE Server"
main: rootmc.net.rootcore.RootCore
depend:
  - DbLib
  - EconomyAPI
  - AdvancedKits

permissions:
  rootcore.*:
    default: false
    children:
      rootcore.rank.*:
        default: op
      rootcore.vipjoin:
        default: op
      rootcore.vipland:
        default: op
      rootcore.command.*:
        default: op
        children:
          rootcore.command.shoprp:
            default: true
          rootcore.command.rp:
            default: true
          rootcore.command.info:
            default: true
          rootcore.command.event:
            default: true